### ISSUE TITLE
Error while trying to ping with a supysonic server

### ISSUE THREAD

**Issue by lxea** [xeals/sunk#2]
Hi I was trying to run the example in the README with my home [supysonic](https://github.com/spl0k/supysonic) server however when it gets to the the .ping() section it panics.

~~I think the issue is that supysonic is expecting the url to be `/rest/{endpoint}.view` in this case `/rest/ping.view` but what it recieves is `/rest/ping`~~

Replacing the auth section with just legacy auth fixes it. I'm not sure why it doesnt work with the new system.

The code im trying to run:
``` rust
    let username = "user";
    let password = "pass";
    let site = "https://music.music.music";

    let client = sunk::Client::new(site, username, password)
        .unwrap();

    client.ping().expect("funk2");

    // Fetch some songs and play them.
    let random = sunk::song::Song::random(&client, 20).unwrap();
    for song in random {
        println!("{:?}", song.album);
    }
```

**Comment by xeals** [comment]
Supysonic's page says

> As Supysonic currently targets API version 1.8.0, the token based method isn't supported.

`sunk` defaults to the token-based auth without actually checking that the server supports it (instead it bases it on the client version). I can either:

- add a configuration to the `Client` that specifies the target API version and properly set it based on that.
- add a soft requirement for a new client to ping the server to check the server's version initially using the legacy auth, then using token auth afterwards if it's supported, but I'd rather not because it's an extra network op every time you build a client.

For both methods, without a more detailed pass, it would be up to the programmer to make sure they only call methods that said target API implements though.

**Comment by lxea** [comment]
I think being able to specify target api method would be simplest, the programmer will have to ensure the server supports the methods anyway if they are targeting non subsonic/subsonic fork based apis like supysonic.

**Comment by xeals** [comment]
0.1.2 will have a `with_target` method added to the client that can manually specify the target API version.

```rust
let cli = Client::new(/* ... */).unwrap().with_target("1.8.0".into());
// ...
```
